### PR TITLE
fix: simdpp/types/empty_expr.h: c++17 compilation fix

### PR DESCRIPTION
**Pull request by michalfapso**
Compiling with `gcc -std=c++17 ` gave an error message.

### CODE REVIEW

**Comment by p12tic** [comment]
Thanks, and sorry for the delay in reviewing.

**Comment by peabody-korg** [comment]
would it be possible to merge this into the dev branch and/or synchronize the dev and master branches?

**Comment by peabody-korg** [comment]
also I get the same error in simdpp/types/generic.h xcode 13.2 at line:


simdpp/types/generic.h:244:52: No viable conversion from returned value of type 'mask_int32<4U>' to function return type 'uint32<4U>'

    SIMDPP_INL operator uint32<N>() const { return eval(); }

**Comment by peabody-korg** [comment]
there are additional errors in empty_expr.h as well. class mask_int64<N, expr_empty> has a similar issue, and the bit_cast solution also appears to resolve it.

**Pull request closed without merging**
