### PR TITLE
implement extract for 64x4 and 32x8

### PR DESCRIPTION
**Pull request by danking**
I'm not sure if I've done this correctly, but I needed extract for AVX2, 256 bit registers. (In particular, I was pop counting the 64bit elements).

### CODE REVIEW

**Comment by danking** [comment]
It seems that 64x4 isn't implemented on any architecture that does not support AVX2. If this is true, then maybe I should IFDEF and only define extract if AVX2 is enabled. Thoughts?

**Comment by danking** [comment]
Hey @p12tic! I really want to work with you to implement a fix for this.

If I submit a patch that only defines extract on 64x4 and 32x8 when AVX2 is enabled, will you merge it? Is there anything I can do (testing, documentation, etc.) to help you gain confidence in merging it?

**Comment by p12tic** [comment]
Hi, sorry for lack of response. The patch looks good to me. I'd like to merge it when the non-rc release is made, which should happen soon.

**Comment by danking** [comment]
@p12tic No problem!

This is great news. We plan to expand our use of this library and this change really cleans up the way we use AVX2 registers.

Thank you!

**Comment by eriksjolund** [comment]
This is not a comment about the pull request itself but I am just showing a sketch of a general workaround that makes use of simdpp::split().
If anyone is interested I could try to clean it up a bit and provide all the source code (including my file lookup_templates.h). I used g++ 7.1 and the compile flag -std=c++1z.

```C++
    #ifndef EXTRACT_HELPER_H
    #define EXTRACT_HELPER_H
    // Copyright Erik Sjolund, Stockholm University
    // License: MIT License

    #include <simdpp/simd.h>
    #include "lookup_templates.h"

    template <unsigned num_bits, unsigned N, unsigned K>
    typename lookup_unsigned<num_bits>::type extract_more_generic(
        const typename lookup_vec<num_bits, N>::type& vec) {
      // libsimdpp does not support simdpp::extract with vectors bigger than 128                                                                                                                            
      // bit.                                                                                                                                                                                               
      // As a workaround we use simdpp::split                                                                                                                                                               
      if
        constexpr(num_bits * N >= 256) {
          typename lookup_vec<num_bits, N / 2>::type half_vec_1{};
          typename lookup_vec<num_bits, N / 2>::type half_vec_2{};
          simdpp::split(vec, half_vec_1, half_vec_2);
          if
            constexpr(K < N / 2) {
              return extract_more_generic<num_bits, N / 2, K>(half_vec_1);
            }
          else {
            return extract_more_generic<num_bits, N / 2, K - (N / 2)>(half_vec_2);
          }
        }
      else {
        return simdpp::extract<K>(vec);
      }
    }
    #endif  // EXTRACT_HELPER_H                   
```

**Comment by p12tic** [comment]
Implemented in bb848d6a91211eb768294ed91612780758ad31a2. Thanks!

**Comment by danking** [comment]
@p12tic Thank you!!

**Pull request closed without merging**
